#!/usr/bin/env python3
"""
gen_commands_doc.py -- docs/COMMANDS.md generated from the commands' own front-matter (C-01).

    python3 tools/gen_commands_doc.py [--check]

--check exits 1 if docs/COMMANDS.md is out of date (used by a test), so the reference cannot drift from the commands.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CMDS = os.path.join(ROOT, "plugin", "generic-tutor", "commands")
OUT = os.path.join(ROOT, "docs", "COMMANDS.md")


def render():
    rows = []
    for fn in sorted(os.listdir(CMDS)):
        if not fn.endswith(".md"):
            continue
        with open(os.path.join(CMDS, fn), encoding="utf-8") as f:
            text = f.read()
        fm = text.split("---\n")[1] if text.startswith("---") else ""
        desc = (re.search(r"^description:\s*(.+)$", fm, re.M) or [None, ""])[1].strip()
        hint = (re.search(r"^argument-hint:\s*(.+)$", fm, re.M) or [None, ""])[1].strip()
        incl = re.findall(r"skills/([\w-]+/[\w.-]+\.md)", text)
        rows.append((fn[:-3], hint, desc, incl))
    lines = ["# Command reference", "",
             "Generated by `tools/gen_commands_doc.py` from the commands' front-matter — edit the command files, not this page.", "",
             "| Command | Arguments | What it does | Loads |", "|---|---|---|---|"]
    for name, hint, desc, incl in rows:
        lines.append(f"| `/{name}` | {hint or '—'} | {desc} | {', '.join(f'`{i}`' for i in incl) or '—'} |")
    return "\n".join(lines) + "\n"


def main(argv):
    text = render()
    if "--check" in argv:
        try:
            with open(OUT, encoding="utf-8") as f:
                return 0 if f.read() == text else 1
        except OSError:
            return 1
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
